version: '3'

services:
  sendrecv-gst:
    build: ./sendrecv/gst
  sendrecv-js:
    build: ./sendrecv/js
    ports:
      - 8080:80
    depends_on:
      - signalling
  signalling:
    build: ./signalling
    ports:
      - 8443:8443
