[package]
name = "gst-rust"
version = "0.1.0"
authors = ["maxmcd <max.t.mcdonnell@gmail.com>"]

[dependencies]
gstreamer = {version = "0.11.2", features = ["v1_14"]}
gstreamer-rtsp-server = "0.11.0"
glib = "0.5.0"
ws = "0.7.6"
